SELECT
    FP.PRODUCT_ID
    , FP.PRODUCT_NAME
    , FO.TOTAL_AMOUNT * FP.PRICE TOTAL_SALES 
FROM 
    FOOD_PRODUCT FP
INNER JOIN (
    SELECT
        PRODUCT_ID
        , SUM(AMOUNT) TOTAL_AMOUNT
    FROM
        FOOD_ORDER
    WHERE
        TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
    GROUP BY
        PRODUCT_ID
) FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY
    FO.TOTAL_AMOUNT * FP.PRICE DESC, FP.PRODUCT_ID