SELECT
    MP.MEMBER_NAME
    , RR.REVIEW_TEXT
    , TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM 
    REST_REVIEW RR
INNER JOIN (
    SELECT
        MEMBER_ID
        , COUNT(1) REVIEW_CNT
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID
    HAVING COUNT(1) = (SELECT MAX(COUNT(1)) FROM REST_REVIEW GROUP BY MEMBER_ID)
) RC ON RR.MEMBER_ID = RC.MEMBER_ID
LEFT OUTER JOIN 
    MEMBER_PROFILE MP
    ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY
    REVIEW_DATE, REVIEW_TEXT