SELECT
    FP.CATEGORY
    , FG.MAX_PRICE
    , FP.PRODUCT_NAME
FROM 
    FOOD_PRODUCT FP
INNER JOIN (
    SELECT
        CATEGORY
        , MAX(PRICE) MAX_PRICE
    FROM
        FOOD_PRODUCT
    GROUP BY
        CATEGORY
) FG
ON FP.CATEGORY = FG.CATEGORY
AND FP.PRICE = FG.MAX_PRICE
WHERE
    FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY
    FP.PRICE DESC