SELECT
    TO_CHAR(OS.SALES_DATE, 'YYYY') YEAR
    , TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM')) MONTH
    , GENDER
    , COUNT(DISTINCT UI.USER_ID) USERS
FROM 
    USER_INFO UI
LEFT OUTER JOIN 
    ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
WHERE
    GENDER IS NOT NULL
    AND OS.SALES_DATE IS NOT NULL
GROUP BY
    TO_CHAR(OS.SALES_DATE, 'YYYY')
    , TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM'))
    , GENDER
ORDER BY
    TO_CHAR(OS.SALES_DATE, 'YYYY')
    , TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM'))
    , GENDER