SELECT
    AU.AUTHOR_ID
    , AU.AUTHOR_NAME
    , BS.CATEGORY
    , BS.TOTAL_SALES
FROM (
    SELECT
        AU.AUTHOR_ID
        , BK.CATEGORY
        , SUM(BK.PRICE * BS.SALES) TOTAL_SALES
    FROM
        BOOK_SALES BS
    LEFT OUTER JOIN
        BOOK BK ON BS.BOOK_ID = BK.BOOK_ID
    LEFT OUTER JOIN
        AUTHOR AU ON BK.AUTHOR_ID = AU.AUTHOR_ID
    WHERE
        TO_CHAR(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY
        AU.AUTHOR_ID, BK.CATEGORY
) BS
LEFT OUTER JOIN
    AUTHOR AU ON BS.AUTHOR_ID = AU.AUTHOR_ID
ORDER BY
    AUTHOR_ID, CATEGORY DESC