SELECT
    CAR_ID
    , AVERAGE_DURATION
FROM (
    SELECT
        CAR_ID
        , ROUND(AVG(DATE_DURATION), 1) AVERAGE_DURATION
    FROM (
        SELECT
            CAR_ID
            , END_DATE - START_DATE + 1 AS DATE_DURATION
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) RH
    GROUP BY
        CAR_ID
)
WHERE
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC, CAR_ID DESC