SELECT
    CRCRH.CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
LEFT OUTER JOIN
    CAR_RENTAL_COMPANY_CAR CRCC
    ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE
    TO_CHAR(CRCRH.START_DATE, 'MM') = '10'
    AND CRCC.CAR_TYPE = '세단'
GROUP BY
    CRCRH.CAR_ID 
ORDER BY
    CRCRH.CAR_ID DESC