SELECT
    DISTINCT CCRH.CAR_ID
    , CASE WHEN RENT.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중' END AVAILABILITY
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CCRH
LEFT OUTER JOIN (
    SELECT
        CAR_ID
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE <= '2022-10-16'
    AND END_DATE >= '2022-10-16'
) RENT ON CCRH.CAR_ID = RENT.CAR_ID
ORDER BY
    CAR_ID DESC
