SELECT
    USER_ID
    , NICKNAME
    , CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS 전체주소
    , REGEXP_REPLACE(TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') AS 전화번호
FROM
    USED_GOODS_USER UGU
LEFT OUTER JOIN (
    SELECT
        COUNT(1) DEAL
        , WRITER_ID
    FROM
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
) UGB ON UGU.USER_ID = UGB.WRITER_ID
WHERE
    UGB.DEAL >= 3
ORDER BY
    USER_ID DESC
