SELECT
    UGU.USER_ID
    , UGU.NICKNAME
    , UGB.TOTAL_SALES
FROM 
    USED_GOODS_USER UGU
LEFT OUTER JOIN
    (SELECT 
        WRITER_ID
        , SUM(PRICE) TOTAL_SALES
     FROM 
        USED_GOODS_BOARD
     WHERE
        STATUS = 'DONE'
     GROUP BY
        WRITER_ID
    ) UGB
    ON UGB.WRITER_ID = UGU.USER_ID
WHERE
    UGB.TOTAL_SALES >= 700000
ORDER BY 
    UGB.TOTAL_SALES