SELECT
    '/home/grep/src/' || GF.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH
FROM
    USED_GOODS_FILE GF
INNER JOIN (
    SELECT
        BOARD_ID
    FROM 
        USED_GOODS_BOARD
    WHERE
        VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
) GB ON GF.BOARD_ID = GB.BOARD_ID
ORDER BY
    FILE_ID DESC