SELECT
    GB.TITLE
    , GB.BOARD_ID
    , GR.REPLY_ID
    , GR.WRITER_ID
    , GR.CONTENTS
    , TO_CHAR(GR.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
FROM 
    USED_GOODS_BOARD GB
INNER JOIN USED_GOODS_REPLY GR
    ON GB.BOARD_ID = GR.BOARD_ID
WHERE
    TO_CHAR(GB.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY
    GR.CREATED_DATE, GB.TITLE