SELECT
    DEPT.DEPT_ID
    , DEPT_NAME_EN
    , ROUND(AVG(SAL), 0) AVG_SAL
FROM
    HR_DEPARTMENT DEPT
INNER JOIN
    HR_EMPLOYEES EMP
    ON DEPT.DEPT_ID = EMP.DEPT_ID
GROUP BY
    DEPT.DEPT_ID
ORDER BY
    AVG_SAL DESC