SELECT
    DISTINCT EMP.EMP_NO
    , EMP_NAME
    , CASE WHEN SCORE >= 96 THEN 'S'
           WHEN SCORE >= 90 THEN 'A'
           WHEN SCORE >= 80 THEN 'B'
           ELSE 'C' END GRADE
    , CASE WHEN SCORE >= 96 THEN SAL * 0.2
           WHEN SCORE >= 90 THEN SAL * 0.15
           WHEN SCORE >= 80 THEN SAL * 0.1
           ELSE 0 END BONUS
FROM
    HR_EMPLOYEES EMP
LEFT OUTER JOIN (
    SELECT
        EMP_NO
        , AVG(SCORE) SCORE
    FROM
        HR_GRADE
    GROUP BY
        EMP_NO
) GRD
ON EMP.EMP_NO = GRD.EMP_NO
ORDER BY
    EMP_NO ASC