SELECT
    DISTINCT CED.ID
    , CED.GENOTYPE
    , PED.GENOTYPE PARENT_GENOTYPE
FROM
    ECOLI_DATA CED
LEFT OUTER JOIN
    ECOLI_DATA PED
    ON PED.ID = CED.PARENT_ID
WHERE
    PED.GENOTYPE & CED.GENOTYPE = PED.GENOTYPE
ORDER BY
    CED.ID ASC